name: Release Plugin

on:
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build plugin
      run: make build
    
    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: date-range-reporter.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
